wxpay:
  appid: wx74862e0dfcf69954
  #商户号
  partner-id: 1558950191
  #商户key
  partner-key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #支付地址
  pay-url: https://api.mch.weixin.qq.com/pay/unifiedorder
  #订单数据地址
  order-url: https://api.mch.weixin.qq.com/pay/orderquery
  #回调地址
  notify-url: http://guli.shop/api/order/weixinPay/weixinNotify
  #支付类型
  trade-type: NATIVE
  #支付域名
  spbill-create-ip: 127.0.0.1

global-config:
  db-config:
    logic-delete-value: 1
    logic-not-delete-value: 0
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_college?serverTimezone=GMT%2B8
    username: root
    password: nansk
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  日志级别
logging:
  root:
    level: info
#feign:
#  hystrix:
#    enabled: true
#hystrix:
#  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000